import os
import django

# Set the settings module
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

# Set up Django
django.setup()

from shelf_life.models import Product


food_items = [
    # Shelf Stable Baby Food Items
    "Cereal: dry mixes",
    "Dry snacks, Puffs",
    "Food in jars, cans",
    "Food in squeeze pouches",
    "Formula",
    "Juice",
    
    # Canned (or Jar Packaged) Food
    "Beans",
    "Fish: salmon, tuna, sardines, mackerel",
    
    # high acid foods
    "Fruit (including applesauce, juices)",
    "Pickles, sauerkraut",
    "Baked beans w/mustard or vinegar",
    "Tomatoes, tomato-based soups and sauces",
  
    # "Low-acid foods",
    "Gravy, soups/broths that aren't tomato based",
    "Pasta, stew, cream sauces",
    "Vegetables (no tomatoes)",

    "Meat: beef, chicken, pork, turkey",
    "Pie filling",
    
    # Aseptically-Packaged Products (Pouch Packaging)
    "UHT Milk",
    "Broth: beef, chicken or vegetable",
    "Soup",
    "Freeze Dried Foods",
    "Fruits; pouch, bag, cup",
    "Meat; fish, tuna, beef, chicken",
    "Pastes; tomato, anchovy",
    "Vegetables; pouch, bag, cup",
    
    # Condiments, Sauces, Syrups
    "Barbeque Sauce (bottled)",
    "Broth; beef, chicken (liquid or paste)",
    "Frosting, plastic tub",
    "Gravy (dry mix envelopes)",
    "Honey",
    "Jams, jellies, preserves",
    "Ketchup, cocktail, or chili sauce: jar, bottle or packet",
    "Mayonnaise: jar, bottle or packet",
    "Olives",
    "Pickles (canned)",
    "Pickles (jarred)",
    "Salad dressings; bottled",
    "Salsa: bottled",
    # "Spaghetti sauce, canned",
    # "Spaghetti sauce, jarred",
    "Syrup (chocolate, corn, pancake)",
    "Vinegar",
    "Worcestershire sauce",
    
    # Dry Goods
    "Baking mix, pancake",
    "Baking mixes (brownie, cake, muffin, pudding, etc.)",
    "Baking powder",
    "Baking soda",
    "Beans, dried",
    "Bouillon: beef or chicken",
    "Bouillon: vegetable",
    "Bread, commercially prepared with preservatives (including rolls)",
    "Bread, fresh from bakery without preservatives",
    "Cakes, commercially prepared",
    "Candy (all, including chocolate)",
    "Casserole Mix",
    "Cereal, cold",
    "Cereal, hot",
    "Chips; potato, tortilla, veggie",
    "Cookies",
    "Cookie Mix",
    "Cornmeal",
    "Crackers",
    "Flour, corn",
    "Flour; potato, rice, white all-purpose",
    "Flour, self-rising",
    "Flour, whole wheat",
    "Fruit, dried",
    "Jerky; animal and plant based",
    "Macaroni and Cheese, mix",
    "Masa flour",
    "Muffin Mix",
    "Nuts, out of shell (bagged)",
    "Nuts, out of shell (canned)",
    "Nuts, in shell",
    "Oats; rolled/quick",
    "Oatmeal; instant",
    "Oil, olive, vegetable, salad",
    "Pasta, dry (egg noodles)",
    "Pasta, dry (no egg)",
    "Pasta; chickpea, lentil (gluten free)",
    "Peanut Butter",
    "Popcorn, kernels",
    "Popcorn, commercially popped and bagged",
    "Popcorn, microwave packets",
    "Potatoes, mashed, instant flakes",
    "Pretzels",
    "Rice, brown",
    "Rice, white",
    "Rice-based mixes",
    "Shortening, vegetable",
    "Spices (whole)",
    "Spices (ground)",
    "Stuffing mix",
    "Sugar, brown (light or dark)",
    "Sugar, confectioners",
    "Sugar; white",
    "Sugar substitute",
    "Toaster pastries (fruit)",
    "Toaster pastries (no fruit)",
    "Taco shells",
    "Tortillas; corn, flour",
    
    # Shelf Stable Beverages
    "Carbonated beverages; soda, seltzer (canned, bottled)",
    "Cocoa Mixes",
    "Coffee creamer, liquid shelf stable",
    "Coffee creamer, powdered",
    "Coffee, ground",
    "Coffee, instant",
    "Coffee, whole bean",
    "Instant breakfast",
    "Juice, bottle, shelf stable",
    "Juice, box",
    "Juice, canned",
    "Juice concentrate, shelf stable",
    "Milk, evaporated",
    "Milk, non-fat dry",
    "Milk, shelf stable UHT",
    "Milk, sweetened condensed",
    "Nutritional aid supplements (Boost, Ensure, etc.)",
    "Plan based (soy, rice, coco nut)",
    "Tea, bagged",
    "Tea, instant",
    "Tea, loose leaf",
    "Water",
    "Water, flavored",
    
    # Dairy and Cooler Items
    "Beverage; Alternative (soy, rice, nut, oat)",
    "Butter",
    "Buttermilk",
    "Cheese trays",
    "Cheese, Cottage",
    "Cheese, Cream",
    "Cheese, Deli sliced",
    "Cheese, hard",
    "Cheese, soft",
    "Cheese, processed sliced, shredded, string",
    "Cheese, ricotta",
    "Coffee creamer, dairy",
    "Cream, Half & Half",
    "Cream, Heavy",
    "Cream, Light",
    "Crust, pie or pizza ready to bake",
    "Deli or Lunch Meat, Retail Packed Only",
    "Dips, made with dairy, mayo, sour cream etc.",
    "Dough, biscuit",
    "Dough, bread or pizza",
    "Dough, cookie",
    "Egg Nog",
    "Eggs, hardboiled",
    "Eggs, in shell",
    "Eggs, pasteurized carton egg substitute",
    "Eggs, pasteurized carton real eggs, unopened",
    "Eggs, whites or yolks",
    "Hummus",
    "Juice, purchased refrigerated",
    "Margarine",
    "Milk",
    "Pasta, fresh",
    "Pesto, jar/tub",
    "Pico de gallo",
    "Pudding, purchased refrigerated",
    "Salad greens, mixed greens, spinach leaves",
    "Salad dressing, refrigerated",
    "Salsa, fresh",
    "Sauces, fresh - pesto, alfredo",
    "Sausage, raw or cooked",
    "Sprouts",
    "Sour cream",
    "Tofu",
    "Whipped Cream, aerosol",
    "Whipped topping, aerosol",
    "Whipped topping, non-dairy tub",
    "Yogurt; dairy-based",
    "Yogurt; plant-based",
    "Yogurt; drinks, pouches",
    
    # Cut Produce
    "Apples, wedged",
    "Berries, blueberries, raspberries, blackberries",
    "Broccoli, florets, stems",
    "Cabbage, shredded",
    "Carrots, baby",
    "Carrots, sticks",
    "Cauliflower, florets",
    "Celery, sticks",
    "Citrus, segmented",
    "Cucumbers, sliced",
    "Garlic, peeled",
    "Grapes",
    "Jicama, sticks",
    "Kiwi, sliced",
    "Lettuce, whole heads",
    "Lettuce salads, whole leaves, small leaf mixes",
    "Mango, cubed sliced",
    "Melon, cubed, sliced",
    "Mushrooms, sliced",
    "Onions; sweet, red, yellow, pearl",
    "Peaches, sliced",
    "Pears, sliced",
    "Peppers, diced, sliced",
    "Pineapple, chunk, diced, sliced",
    "Pomegranate, arils",
    "Potatoes, peeled",
    "Root mixtures",
    "Spinach, leaves",
    "Squash, cubed, sliced",
    "Strawberries, sliced",
    "Tomatoes, diced",
    "Zucchini, cubed, sliced",
    
    # Items Purchased Frozen
    "Bacon",
    "Bread, Bagels",
    "Chicken, pieces",
    "Chicken, whole",
    "Chicken, nuggets/patties",
    "Desserts, frozen baked goods",
    "Desserts, frozen cream pies",
    "Dinners: pies, casseroles, shrimp, ham, pork or sausage",
    "Dinners: beef, turkey, chicken or fish",
    "Dough, bread",
    "Dough, cookie",
    "Eggs; pasteurized in cartons",
    "Fish, breaded",
    "Fish, finned, fatty; salmon, tuna",
    "Fish, finned, lean; cod, halibut",
    "Fish, finned, lean; pollock, perch, trout",
    "Fruit, frozen",
    "Ham, fresh, uncured, cooked",
    "Ham, fresh, uncured, uncooked",
    "Ham, cooked, store wrapped, vacuum packed",
    "Hot dogs",
    "Ice Pops",
    "Ice Cream",
    "Juice concentrate",
    "Luncheon meat",
    "Meat, ground beef, pork, poultry",
    "Meat, beef, veal, lamb, pork; chops, roasts, steaks",
    "Potato products; fries, hashbrowns",
    "Prosciutto, Parma or Serrano ham, dry Italian salami",
    "Sausage, raw or cooked",
    "Shellfish; crab, lobster",
    "Shellfish; shucked clams, oysters, mussels, scallops",
    "Shellfish; shrimp",
    "Soups and stews, vegetable or meat based",
    "Soy meat substitutes",
    "Vegetables, cut/diced",
    "Waffles, pancakes",
    "Whipped topping, non-dairy tub",
    
    # Meats, Fresh
    "Fish, finned, fatty; salmon, tuna",
    "Fish, finned, lean; cod, halibut",
    "Fish, finned, lean; pollock, perch, trout",
    "Shellfish, shrimp; cooked (cocktail shrimp)",
    "Shellfish, shrimp; raw",
    "Crab, canned",
    "Crab, in the shell; whole, legs, claws",
    "Shellfish, shucked; oysters, clams, mussels",
    "Lobster Tails, raw",
    "Scallops, raw",
    
    # Fish/Seafood, Cooked
    "Fish, finned, fatty: salmon, tuna",
    "Fish, finned, lean; cod, halibut",
    "Shellfish, shrimp; cooked (cocktail shrimp)",
    
    # Meats, Raw
    "Beef Roasts",
    "Beef Steaks",
    "Pork Roasts",
    "Pork Chops",
    "Lamb Roasts",
    "Lamb steaks/Chops",
    "Poultry: Chicken or Turkey, whole",
    "Ground Meats (beef, pork, lamb, or poultry)",
    
    # Meats, Processed
    "Bacon, unopened",
    "Bacon, deli or butcher block",
    "Chicken, fried, deli",
    "Ham, unopened",
    "Hot Dogs, unopened",
    "Luncheon Meats, deli sliced",
    "Luncheon Meats, unopened commercial package",
    "Pepperoni, salami",
    "Pouch or container, cooked; beef, chicken, pork",
    "Sausage, raw",
    "Sausage, smokes links or patties",
    
    # Wild Game
    "Venison, Elk",
    "Rabbit, Squirrel",
    "Wild duck, pheasant, goose (whole)",
    
    # Prepared Foods / Deli Foods
    "Chicken, Roasted or Fried",
    "Deli Meat, retail packaged",
    "Guacamole",
    "Hummus, Pasteurized",
    "Hummus, with Preservatives",
    "Hummus, traditional, no preservatives, not pasteurized",
    "Main dishes, meals",
    "Meats in gravy or broth (including meat pies)",
    "Pasta, fresh",
    "Salads, prepared (macaroni, egg, potato, chicken, tuna, etc.)",
    "Sandwiches, Grab & Go, Retail packaged",
    "Sauces, Egg-Based (Hollandaise, etc.)",
    "Side dishes, cooked vegetables",
    "Side dishes, potato-based (not salad)",
    "Side dishes, rice",
    "Soups, Stews"
]
# cycle through each item in the database, display the item name
# from shelf_life.models import Product
# for item in Product.objects.all():
#     print(item.item_name)
#     input = "baby food?"
#     if input ==

# for name in food_items:
#     product, created = Product.objects.get_or_create(item_name=name)

#     if created:
#         print(f"✅ Created: {name}")
#     else:
#         print(f"↩️ Already exists: {name}")