# Generated by Django 5.2.4 on 2025-07-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255, unique=True)),
                ("baby_food", models.BooleanField(default=False)),
                (
                    "shelf_stable_shelf_life",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "shelf_stable_subcategory",
                    models.CharField(blank=True, max_length=100),
                ),
                ("shelf_stable_lower", models.IntegerField(blank=True, null=True)),
                ("shelf_stable_upper", models.IntegerField(blank=True, null=True)),
                ("shelf_stable_note", models.TextField(blank=True)),
                ("frig_shelf_life", models.CharField(blank=True, max_length=100)),
                ("frig_subcategory", models.CharField(blank=True, max_length=100)),
                ("frig_lower", models.IntegerField(blank=True, null=True)),
                ("frig_upper", models.IntegerField(blank=True, null=True)),
                ("frig_note", models.TextField(blank=True)),
                ("frozen_shelf_life", models.CharField(blank=True, max_length=100)),
                ("frozen_subcategory", models.CharField(blank=True, max_length=100)),
                ("frozen_lower", models.IntegerField(blank=True, null=True)),
                ("frozen_upper", models.IntegerField(blank=True, null=True)),
                ("frozen_note", models.TextField(blank=True)),
            ],
        ),
    ]
