# Generated by Django 5.2.4 on 2025-07-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="baby_food",
        ),
        migrations.AddField(
            model_name="product",
            name="baby_food_lower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="baby_food_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="baby_food_shelf_life",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="baby_food_subcategory",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="baby_food_upper",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
