# Generated by Django 5.2.4 on 2025-07-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shelf_life",
            "0002_remove_product_baby_food_product_baby_food_lower_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="baby_food_subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="frig_subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="frozen_subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelf_stable_subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
