# Generated by Django 5.2.4 on 2025-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0003_alter_product_baby_food_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
