# Generated by Django 5.2.4 on 2025-07-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0004_product_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, default="Anonymous", max_length=100),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
