# Generated by Django 5.2.4 on 2025-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
