# Generated by Django 5.2.4 on 2025-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0006_alter_comment_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
