# Generated by Django 5.2.4 on 2025-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0008_productview"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
