# Generated by Django 5.2.4 on 2025-08-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelf_life", "0009_product_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductView",
        ),
    ]
